Assistants v2
RageAgainstThePixel/com.openai.unity pull request #224
Opened 2024-04-30 13:17 UTC by dnnkeeper

This is a small rough update to v2 beta helpers with support for delta streaming and new authorization using project keys. It also includes updates to AudioTranscriptionRequest to handle encoded audio streams (I'm using Vorbis encoding in my project, which I may post later as a sample).
I don't have time to create proper test cases and documentation, so use this branch as a reference for future updates if you find it useful.

2024-04-30 13:26 UTC, StephenHodgson commented on OpenAI/Packages/com.openai.unity/Runtime/Authentication/OpenAIAuthInfo.cs
> +        public OpenAIAuthInfo(string apiKey, string organizationId = null, string project = null)
does this id have a prefix?

2024-04-30 13:26 UTC, StephenHodgson commented on OpenAI/Packages/com.openai.unity/Runtime/Audio/AudioTranscriptionRequest.cs
> +            : this(audioStream, $"UserSpeech.wav", model, prompt, responseFormat, temperature, language, timestampGranularity)
make file name required param

2024-04-30 13:27 UTC, StephenHodgson commented on OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs
> +                { "OpenAI-Beta", "assistants=v2"}
these changes should be broken out into a separate PR from the projectId changes

2024-04-30 13:27 UTC, StephenHodgson commented on OpenAI/Packages/com.openai.unity/Runtime/OpenAIClient.cs
> +        public static JsonSerializerSettings JsonSerializationOptions { get; } = new()
revert

2024-04-30 13:28 UTC, StephenHodgson requested changes
Most of these changes are breaking and will be done in 8.x which needs to first be completed upstream in [OpenAI-DotNet](https://github.com/RageAgainstThePixel/OpenAI-DotNet)

2024-05-02 18:01 UTC, ElisMia commented
> Most of these changes are breaking and will be done in 8.x which needs to first be completed upstream in [OpenAI-DotNet](https://github.com/RageAgainstThePixel/OpenAI-DotNet)

That would be awesome.  Do you know when version 8 will be available?

2024-05-02 18:24 UTC, StephenHodgson commented
> That would be awesome. Do you know when version 8 will be available?

Hard to say as I do this in my free time.

2024-05-14 09:17 UTC, Bodekaer commented
@dnnkeeper would this temporary PR add support for Assistants v2 as well? 
Info: https://platform.openai.com/docs/assistants/migration

2024-05-23 18:15 UTC, StephenHodgson commented
Closing this in favor of #235

2024-05-23 18:15 UTC, closed without merging